name: tensorflow
store: /user-environment
description: Tensorflow for GH200
spack:
  repo: https://github.com/spack/spack.git
  commit: d66dce2d668a6234504594661506cdd1eaca4adc
  #commit: develop
  #commit: releases/v0.22
modules: false
