pytorch:
  compiler:
  - toolchain: gcc
    spec: gcc@12.3
  mpi:
    spec: cray-mpich@8.1.30
    gpu: cuda
  unify: true
  specs:
  - aws-ofi-nccl@master
  - cmake
  - cuda
  - nccl
  - ninja
  - protobuf@3.25.3
  - python
  - py-numpy
  - py-tensorflow +nccl
  - llvm ~cuda
  - py-libclang
  - deepmd@2.2.11 +tensorflow
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    pytorch:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
