pytorch:
  compiler:
  - toolchain: gcc
    spec: gcc@12.3
  mpi:
    spec: cray-mpich@8.1.30
    gpu: cuda
  unify: true
  specs:
  - aws-ofi-nccl@master
  - cmake
  - cuda@12
  - cray-mpich
  - nccl
  - ninja
  - protobuf@3.25.3
  - python@3.11
  - py-numpy
  - py-tqdm
  - py-lightning
  - py-typing-extensions
  - py-torch@2.3 +distributed +cuda cuda_arch=90 +cudnn +nccl +mpi
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    pytorch:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
