gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc
      - toolchain: llvm
        spec: nvhpc
  mpi:
      spec: cray-mpich@8.1.30%nvhpc
      gpu: cuda
  unify: true
  specs:
  - aws-ofi-nccl@master
  - cmake
  - cuda@12.4
  - fftw%nvhpc +openmp
  - fmt
  - hdf5+hl+mpi
  - libtree
  - meson
  - nccl
  - nccl-tests
  - ninja
  - nvpl-blas threads=openmp
  - nvpl-lapack threads=openmp
  - osu-micro-benchmarks@5.9
  - python@3.12
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    default:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
