prgenv-nvidia:
  compiler:
    - toolchain: gcc
      spec: gcc
    - toolchain: llvm
      spec: nvhpc
  unify: true
  mpi:
    spec: cray-mpich@8.1.30%nvhpc
    gpu: cuda
  packages:
  - perl
  - curl
  - gmake
  - autoconf
  - automake
  specs:
  - osu-micro-benchmarks@5.9%nvhpc
  - cuda@12
  - python@3.10
  - eccodes@2.25.0%nvhpc +tools +fortran +aec +openmp jp2k=jasper
  - netcdf-c@4.9.2
  - netcdf-fortran@4.6.1%nvhpc
  - hdf5%nvhpc +szip +hl +fortran +mpi
  - openblas@0.3.21%nvhpc
  - libfyaml
  - nco@5.0.1
  - cdo@2.0.5
  # the following are explicitly set for backwards compatibility
  - cray-pals@1.2.12
  variants:
  - cuda_arch=80
  - +mpi
  - +cuda
  views:
    prgenv-icon:
      link: roots
